Layout/LineLength:
  Max: 120
  IgnoredPatterns: ['(\A|\s)#']
  Exclude:
    - 'db/seeds.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

Metrics/AbcSize:
  Max: 20

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true
