default: &default
  adapter: postgresql
  encoding: unicode
  host: world-db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
